server:
  port: 6999
eureka:
  instance:
    hostname: eureka6999
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7000:7000/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000